#!/bin/sh
#
# Umph::Prompt
# Copyright (C) 2011  Toni Gundogdu <legatvs@gmail.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.
#

# wrap - Umph::Prompt wrapper script

note()
{
  echo "Run in the top source directory of Umph::Prompt."
  exit 0
}

usage()
{
  echo "Usage: $0 [perl-script]
Example: $0 examples/foo.pl"
  note
}

[ $# -lt  1 ] && usage
[ -d lib ] || note

export PERL5LIB=$PERL5LIB:`pwd`/lib
#echo $PERL5LIB

perl $@

# vim: set ts=2 sw=2 tw=72 expandtab:
